name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  deploy:
    name: Deploy Project to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --token TZzYxkUyZbouMdKwHigvrVVs --confirm
        env:
          VERCEL_PROJECT_ID: prj_tX8CHnBNFp4bGru6KnI5pCIkxmyC
